### ISSUE TITLE
[QUESTION] Nested dictionary updates.

### ISSUE THREAD

**Issue by Huffmaar** [betteridiot/b575f19#19]
# Instructions
* The more information/context you provide, the better we (the instructors and class) can collectively assist you.

* Please fill out all of the relevant sections below. Incomplete questions will not be addressed by the instruction team. 

* Questions asked ***without*** showing an attempt to answer individually will also not be addressed.

* It is bad etiquette to ask things such as "I don't know how to do this, can you tell me how?" or "I can't get this code to work, what is wrong?" if you do not provide the context and/or screenshots necessary to 
help. 

---
# Question (continued)
Currently when iterating through my deepest dictionaries gene_positions[<index>][<'type'>]['counts'] it applies to all instances with gene_positions. I found a way to do so by importing collections with the 'makehash' function when poking online. I haven't used this yet
My first question would be why a separate function is needed to do this?
My second question is if I can use the above recommendation while remaining within the UoM honor code? I am assuming that the answer is no unless otherwise specified. More broadly, I have been interpreting the UoM Academic Honor Code as restricting information from only help(), correspondence with you two, or documents provided for class via GitHub or Canvas. Is that too restrictive of an understanding?

```python
# Paste your code in this code block (if needed)

```

---
# What do you have?
Use this space to describe what resources/functions/code you have that you feel may be relevant to answering this question. 

**Additionally**, if this is a coding question, describe what **input** this problem section of code requires. By "input", we mean what `type` of data it is.

```python
# Paste your code in this code block (if needed)

```

---
# What do you need?
Use this space to describe what resources/functions/code/data you believe is required to determine if this question has been solved.

**Additionally**, if this is a coding question, describe what **output** this problem section of code requires. By "output", we mean what `type` of data it is.

```python
# Paste your code in this code block (if needed)

```

---
# What have you done?
Use this space to describe what approaches you have done in your attempts to solve this question yourself. This is the **most important* part of your question.

## If this is just a general question
Describe what your *hypothesis* of what the answer is here

## If this is a coding question
We require you to post your code, error messages, and output of your code here.

### User-written code
```python
# Paste your code here (Removed assignment code, can resend if you want.)
dictionary1 = {'a':1, 'b':2, 'c':3}
dictionary2 = {'a':2, 'b':3, 'c':4}
nested_dictionary = {'abc':dictionary1, 'bcd':dictionary2}
nested_dictionary_alt = nested_dictionary
list_of_nested_dictionary = [nested_dictionary, nested_dictionary_alt]
print(list_of_nested_dictionary)
list_of_nested_dictionary[1]['abc'].update({'a':12})
print(list_of_nested_dictionary)


```

### Observed error messages
```python-traceback
# Paste the observed error messages here

```

### Observed output of code (other than error messages)
```python
# Paste the output of your coding attempts here
[{'abc': {'a': 1, 'b': 2, 'c': 3}, 'bcd': {'a': 2, 'b': 3, 'c': 4}}, {'abc': {'a': 1, 'b': 2, 'c': 3}, 'bcd': {'a': 2, 'b': 3, 'c': 4}}]
[{'abc': {'a': 12, 'b': 2, 'c': 3}, 'bcd': {'a': 2, 'b': 3, 'c': 4}}, {'abc': {'a': 12, 'b': 2, 'c': 3}, 'bcd': {'a': 2, 'b': 3, 'c': 4}}]
```

---
# Checklist
Replace the space in between the brackets with an X
* [x] Identified what you already have available to address this question
* [x] Identified what you need to reach an acceptable answer
* [x] Shown what you have done up to this point
    * [ ] A hypothesis if this is a general question
    * [ ] Your code, error messages, and output if this is a coding question

**Comment by betteridiot** [comment]
This is an empty question

**Comment by Huffmaar** [comment]
Yeah, I accidentally submitted it before I could fill it the form. I also spent too long making phrasing my questions, for that I apologize.

**Comment by Huffmaar** [comment]
> 
> 
> This is an empty question

I have filled my empty question using an example that doesn't reveal my code.
Ideally, I would like to know why it insists on updating all entries like this despite specifying only one.

**Comment by betteridiot** [comment]
1. You shouldn't have to import any other functions or use anything we haven't covered in class or introduced in this homework to solve this problem
1. Thank you for "hiding" your original code. That is much appreciated.
1. I am assuming the problem is actually in your `initialize_positions` function:
    * if one were to do the following example, they would get a list of 5 _references_ to the _same_ dictionary:
```python
some_dict = {'marcus': 'GSI', 'cristina': 'Lecturer'}
some_list_of_dicts = [some_dict for i in range(5)]

# See if it looks right
print(some_list_of_dicts)

# Modify a single element of the list at the 2th index
some_list_of_dicts[2]['picard'] = 'captain'

# Seems right
print(some_list_of_dicts[2])

# But isn't
print(some_list_of_dicts)
```
This is not what we want, right?

To fix this, we need to make dictionaries that are identical in structure, but independent of each other:
```python
# Initialize the list. Notice that I did not create an intermediate variable of the dictionary
# Rather, I just did it inline
new_list_of_dicts = [{'marcus': 'GSI', 'cristina': 'Lecturer'} for i in range(5)]

# See if it looks right
print(new_list_of_dicts)

# Modify a single element of the list at the 2th index
new_list_of_dicts[2]['picard'] = 'captain'

# Seems right still
print(new_list_of_dicts[2])

# Final sanity check
print(new_list_of_dicts)
```

**Comment by betteridiot** [comment]
An illustration of what is happening in your code is you created a folder on your computer with 4.2 million _shortcuts_ to the same exact file instead of of 4.2 million copies of the same exact file. (Heh, kind of like a stereotypical Mac user's desktop)

While they both _appear_ to be correct, only one actually has 4.2 million independent files, where the other has 4.2 million ways to look at the same file.

**Comment by betteridiot** [comment]
As far as the [UMich academic honesty policy](https://rackham.umich.edu/academic-policies/section8/), any code found on SO/SE/Google would not be considered your own (unless you are the author)...but this applies if and only if you try to submit it as your own. 

_However_, just like research, citing your resources is perfectly allowable as long as you do not plagiarize the content directly.

**Comment by Huffmaar** [comment]
> 
> 
> As far as the [UMich academic honesty policy](https://rackham.umich.edu/academic-policies/section8/), any code found on SO/SE/Google would not be considered your own (unless you are the author)...but this applies if and only if you try to submit it as your own.
> 
> _However_, just like research, citing your resources is perfectly allowable as long as you do not plagiarize the content directly.

Is there a standardized format for citing code (I am familiar how to do so with papers but not with code)? This aside from the actual assignment but I would like to know.

**Comment by betteridiot** [comment]
Again, you _shouldn't_ need to use any outside resources. But, in the event that you _really_ need to; Put a comment line above/below/beside the code in questions that contains the reasoning for its usage and the URL you got it from.

**Comment by betteridiot** [comment]
As far as standard format, to put it shortly: no.

Technically, any code that doesn't have an attached license cannot be used by any party other than the author. Depending on the license (if there is one), certain stipulations for citation/attribution are detailed within.

With regards to SO/SE _specifically_, all code falls under the [CC-BY-SA license](https://creativecommons.org/licenses/by-sa/2.0/) which states:
> "Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use. "

**Comment by Huffmaar** [comment]
I have moved onto new and more exciting errors involving memory. Thanks for the help so late on why it was misbehaving.
